### ISSUE TITLE
Exported matrix not showing up correctly in editor

### ISSUE THREAD

**Issue by neowcr** [NotBestLord/Matrixs#1]
Code:
```
@tool
class_name BattleSkill extends Resource;

@export var weight = 5;
@export var condition = 0;
@export var matrix : MatrixBool
```

How it's showing up:

![Captura de tela 2024-10-20 004611](https://github.com/user-attachments/assets/cb4efe02-9b51-4da8-aeeb-0ad2eb7ef15f)

Godot v4.3.stable.official [77dcf97d8]

**Comment by NotBestLord** [comment]
Hello, i cannot replicate this behavior with this code. 

Can you make sure the plugin is enabled? (Project Settings > Plugins), after enabling the matrix should show up properly.

**Comment by neowcr** [comment]
It worked, huge thanks! Super glad I was able to found the perfect plugin for my nice use case, and it now works perfectly
